### ISSUE TITLE
Only getting JS logo when using localhost:8080 or LANIP:8080

### ISSUE THREAD

**Issue by mpender** [treyyoder/quakejs-docker#10]
I must have missed something but using stock directions doesnt work, just getting logo on different browsers

**Comment by treyyoder** [comment]
Are there any errors in the browser console, or in the container log?

**Comment by mpender** [comment]
First off, thanks for the hard work and the quick response. I feel this is a user error on my part :) 

Container log of interest : 
execing default.cfg
couldn't exec q3config_server.cfg
couldn't exec autoexec.cfg
fs_game is write protected.
Hunk_Clear: reset the hunk ok
^3Couldn't write (null)/ioq3_server.pid.
Com_RandomBytes: using weak randomization
--- Common Initialization Complete ---
Hostname: emscripten
IP: 172.29.1.0
Opening IP socket: 0.0.0.0:27960
ignoring setsockopt command
tty console mode disabled
execing server.cfg
sv_maxclients will be changed upon restarting.

No major issues in browser console.

Im trying an EC2 instance instead of doing it local to see how it goes

**Comment by mpender** [comment]
Ok, im an idiot. 

docker run -d --name quakejs -e SERVER=10.0.0.2 -e HTTP_PORT=8080 -p 8080:80 -p 27960:27960 treyyoder/quakejs:latest

SERVER should be whatever your machine is, now it works..
