### ISSUE TITLE
Adding new serverside mod

### ISSUE THREAD

**Issue by Locustv2** [treyyoder/quakejs-docker#14]
I was trying to host a game with Noghost mod and noticed that the pk3 should be added to the public manifest.
Or to have another content server. Can help with that? i am trying to build everything according to the instructions on quake js repo, but the dependencies used are nowhere to be found. Using the latest emscripten gives a chain of errors.

Would it be possible to add the NoGhost server side mod to the public manifest? http://noghost.net

There are several server side enhancements to provide a smoother gameplay as well as a lot of mods to play.

We used to play this mod mostly on point of release 1.16n. And this was compatible with quake 3 demo as well as quake 3 1.11.

However afaik the ioq3 is based on 1.32 point of release. so i am not sure if this can be converted.

However there is a serverside mod for both:

1.16 / 1.11 / demo : http://www.noghost.net/modfiles/1.16/NoGhost.zip

1.32: http://www.noghost.net/modfiles/1.32/NoGhost_beta.zip (it says beta but this has been used for a while and didn't get an update afaik)

or just to add NoGhost like a mod (similar to CPMA) then we can just use fs_game

**Comment by mwojtynek** [comment]
Do you have a solution? Since there are some NoGhost servers out there.

**Comment by Locustv2** [comment]
@mwojtynek where did you find NoGhost Servers?

**Comment by mwojtynek** [comment]
http://www.quakejs.com

**Comment by Locustv2** [comment]
@mwojtynek ahh yeah these are my servers. If you are interested take a look at: https://github.com/Locustv2/NoGhost/tree/1.32/tweaks

This branch is the exact same that's running on quakejs. Which means the configs that you see on the branch are exactly what's being used (including the rconpassword). So i would request that you don't go around my servers and abusing rcon priviledges :D

**Comment by treyyoder** [comment]
Closing stale issue.
