### ISSUE TITLE
entrypoint.sh is missing exec permission

### ISSUE THREAD

**Issue by ENT108** [treyyoder/quakejs-docker#5]
```standard_init_linux.go:211: exec user process caused "exec format error"```

Docker quits with this error.

## Expected

Docker runs :)

#### Edit
Yes, I just pulled the image.

**Comment by treyyoder** [comment]
Can you post the command you are using to start the container?

**Comment by ENT108** [comment]
```docker run -d --name quakejs -e SERVER=192.168.1.225 -e HTTP_PORT=8080 -p 8080:80 -p 28960:27960 treyyoder/quakejs:latest```

I rebuild the image with +x on entrypoint.sh and it just works.

I run Raspbian on a pi.

**Comment by treyyoder** [comment]
Yeah, I'm having trouble with compatibility between Windows and Linux in regards to making entrypoint.sh executable.  Ill need to investigate this more.

**Comment by treyyoder** [comment]
I was unable to recreate your exact error, but I was able to fix my issue by changing the EOL conversion.  I updated the readme, but you have to use LF for Dockerfile and entrypoint.sh

I've updated the image in dockerhub, try giving that a go.
