### ISSUE TITLE
Only one map is working

### ISSUE THREAD

**Issue by treyyoder** [treyyoder/quakejs-docker#6]
Sorry guys, just realized that only one map is working.  Working on it now.

**Comment by treyyoder** [comment]
Fixed

**Comment by 5280Pipedream** [comment]
Just pulled the latest image and this issue still persists.

**Comment by ps-mariotacke** [comment]
@5280Pipedream: i got it to work by fully deleting the image and re-pulling it PLUS changing my server.cfg to https://github.com/treyyoder/quakejs-docker/commit/8fe0ef3fb5ec88b33efb7471ae2b1ae6bb4facd2
