### ISSUE TITLE
Custom Maps

### ISSUE THREAD

**Issue by stevezau** [treyyoder/quakejs-docker#7]
Hi, thanks for your work on this. Makes it really easy.

Are there any plans to allow additional map support? Or instructions on how you can add custom maps?

Thanks

**Comment by 5280Pipedream** [comment]
+1

**Comment by briancullinan** [comment]
Would you rather have a solution that attaches to a directory and then does the conversion on start? Assets are converted to make them quicker to load in the browser and takes up less memory, and downloads faster.

**Comment by mortenrpetersen** [comment]
I'm also interested in this.

**Comment by briancullinan** [comment]
My startup script runs with an option called `--no-overwrite` where it unpacks pk3s the first time and subsequent runs it only checks if the files exist. New pk3s can be added and unpacked. 

https://github.com/briancullinan/planet_quake/blob/master/code/xquakejs/bin/start.sh

The docker file builds from sources and only copies the required files for hosting. So you can delete the intermediate images to save on storage.

https://github.com/briancullinan/planet_quake/blob/master/Dockerfile

Or run from docker hub

```
docker run -ti -v ~/Quake3e:/tmp/Quake3e -v /Applications/ioquake3/baseq3:/tmp/baseq3 -p 8080:8080 -p 1081:1081 -p 27960:27960/udp --name quake3e briancullinan/quake3e:latest
```
I suppose I could write to a specific output directory that you can mount a volume to. Right now the converted files stay inside the docker image.

**Comment by 5280Pipedream** [comment]
Looks great @briancullinan. I'll give this a shot. Thanks!

**Comment by timdonovanuk** [comment]
> https://github.com/briancullinan/planet_quake/blob/master/code/xquakejs/bin/start.sh

This script is a 404 now :(

I don't suppose anyone could help document how to load maps into the docker image? Written from the point of view of someone that stumbled across the quakejs docker repo and that's about as far as their knowledge goes!

**Comment by treyyoder** [comment]
I think this topic is better suited as a [discussion](https://github.com/treyyoder/quakejs-docker/discussions/23) rather than an issue.  If anyone has implemented this let's talk about it. 

If anyone has artifacts from @briancullinan, please share.
