### ISSUE TITLE
Only QuakeJS logo

### ISSUE THREAD

**Issue by mortenrpetersen** [treyyoder/quakejs-docker#9]
Hi, I have no errors on this container in docker. However when i go to the ip adress, all I get is the QuakeJS logo.

Any idea on what could be wrong?

**Comment by kevenwyld** [comment]
In case anyone lands here and is stuck with the same thing, you have to navigate to the address you set in the `SERVER` env var when launching the container.  Going to `localhost:<port>` or `172.0.0.1:<port>` will not proceed past the splash logo.

I overlooked this detail in the readme when trying to get it to work.

**Comment by xytrux** [comment]
This happens on Render.
